---
version: "3"
services:
  pws-idokep-dispatcher:
    image: peterzen/pws-idokep-dispatcher
    environment:
      - USERNAME=idokep_username
      - PASSWORD=idokep_pass
      - PWS_IP=10.10.10.10
      - FETCH_INTERVAL=300
    restart: unless-stopped
